Implement queue structure to match below given scenario. And implement add_order, prepare_next_order, and check_status functionalities.

EatItNow restaurant is trying to automate their food preparing pipeline. Once waiter received order from the customer, waiter will add that to the system using add_order function. 
add_order function will take table_number (integer), meal_number (integer) and waiter_id (integer) as parameters in order to add details into the system.
And orders will be saved in first come first serve order.

There is only one chef in the kitchen, he is only capable of processing one order at a given time. chef will use prepare_next_order function to get the next order that available in the system. Calling prepare_next_order function will return table_id, waiter_id and meal_id to the chef.

There is another function called check_status to check what is the status of the order, after providing table_number this function will provide status of the order. If it is already taken by the chef using prepare_next_order function then status will be preparing. Or otherwise it is still in the queue structure. It will provide what is the location of the order in queue. 

You can't use inbuild python queue functions like .pop() and .dequeue()

In [80]:

def main():
    
    import numpy as np 
   
   
    global q 
    
    q= np.zeros((0,3), dtype=int)
    print(q)

    
    
    
    
    
    def add_order(table_number, meal_number, waiter_id):
        global q 
        q = np.append( q, np.array([[table_number, meal_number, waiter_id]]), axis=0)
        # print(q)
        
        return q

    
    
    def prepare_next_order():
        
        global q
        
        f_q = q[0,:]
        print("first colunm", f_q)
        
        
        [table_number, meal_number, waiter_id] = f_q
        print("table_number : ",table_number,"meal_number : ",meal_number, "waiter_id : ",waiter_id)
        print('Old q ', q)
        q = np.delete(q, 0, 0)
        print('new q ', q)
        
        
        
          # identify the final row
        
            # get the parameters
    
            # remove the first row 
        
        return table_number, meal_number, waiter_id
    
  
    
    
    
    def check_status(table_number):
        # Extract the firt column 
        # check if it is in the colunm
        # if no its in the preaparation process
        # if yes 
            # find the posiion of the array
        
        table_numbers_in_que = q[:,0].T
        print("table_que", table_numbers_in_que)
        
        position = np.where(q==table_number)
        print(position[0][0])
        
        if position == None :
            print("Food is processing")
            status = "Food is processing" 
        else :
            print("Your que position is ",position[0][0])
            status = "Your que position is ",position[0][0]
        
        
        
        
        
            
        
        return status
    
   
    add_order(1,1,1)
    add_order(2,2,2)
    add_order(3,3,3)
    add_order(4,4,4)
    prepare_next_order()
    status = check_status(2)
    print(status)
    
 
 
    
    
    
    
    
    
#     pass

main()




[]
first colunm [1 1 1]
table_number :  1 meal_number :  1 waiter_id :  1
Old q  [[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
new q  [[2 2 2]
 [3 3 3]
 [4 4 4]]
table_que [2 3 4]
0
Your que position is  0
('Your que position is ', 0)
